setting up server
votingworks/election-results-reporting pull request #8
Opened 2021-08-20 17:26 UTC by MorganLove

Setting up the server and client directories.

2021-08-21 01:30 UTC, MorganLove commented
A lot of this is copied over from Arlo, and so I tried renaming arlo-specific terms to Election Results Reporting specific terms... but I'm not sure that ERR is the best acronym. It just feels like errors all over the place. :stuck_out_tongue_closed_eyes: Any ideas?

2021-08-24 19:05 UTC, benadida commented
> A lot of this is copied over from Arlo, and so I tried renaming arlo-specific terms to Election Results Reporting specific terms... but I'm not sure that ERR is the best acronym. It just feels like errors all over the place. 😝 Any ideas?

yeah that's an interesting problem! Maybe `ereporting` ?

2021-08-24 19:15 UTC, benadida requested changes
Some Arlo graphics copied over that don't need to be here.

A good bit of Arlo code remains, let's trim this down a good bit more before merging.

2021-08-24 19:15 UTC, benadida commented on .gitignore
> +*.swp
these should go in a personal `.gitignore`. Otherwise we have to include all the other patterns (emacs, etc.)

2021-08-24 19:15 UTC, benadida commented on Procfile
> +slack_worker: python -m server.activity_log.slack_worker
let's remove the background and slack workers until/unless we need them.

2021-08-24 19:15 UTC, benadida commented on app.json
> +    }
same, remove this until we need it.

2021-08-24 19:15 UTC, benadida commented on client/LICENSE
> +                       Version 3, 29 June 2007
probably copy/paste, let's not have a second license file in here, let's remove this file.

2021-08-24 19:15 UTC, benadida commented on client/src/App.tsx
> +      <img height="50px" src="/arlo.png" alt="Election Results Reporting, by VotingWorks" />
some Arlo stuff remains :)

2021-08-24 19:15 UTC, benadida commented on client/src/App.tsx
> +        </p>
this language is still Arlo. Are you meaning to change this later? I don't see a good reason to keep that in the changelog, so I suggest changing that right away.

2021-08-24 19:15 UTC, benadida commented on client/src/components/UserContext.tsx
> +import React, {
lots of Arlo-specific stuff in here.

2021-08-24 19:15 UTC, benadida commented on client/src/setupProxy.js
> +  app.use(proxy('/auditboard/*', { target }))
arlo specific URL

2021-08-24 20:35 UTC, MorganLove commented
@benadida thanks! I trimmed a lot of arlo-specific stuff down, but I knew I was missing a bunch, haha. `ereporting` sounds better, maybe `elreporting` so it's obvious it's not error-reporting?

2021-08-24 20:42 UTC, benadida commented
@MorganLove yeah! How about `elrep` for short?

2021-09-08 22:28 UTC, benadida approved these changes
Still 5 instances of "Arlo", let's get those removed.

I don't see a data model file: do we have jurisdictions in the same way as for Arlo?

This is a large PR, which makes it hard to review, but I do want to move forward, so if the code works for you, let's move forward and then let's schedule some time to go through the code structure together so I can provide a bit more detailed feedback.

2021-09-08 22:28 UTC, benadida commented on app.json
> +    }
I don't think we have a worker yet, right? Let's remove it from the formation for now.

2021-09-10 22:06 UTC, merged